### PR TITLE
Activate the user after importing it

### PR DESCRIPTION
**Pull request by ajimix**

### CODE REVIEW

**Comment by vindia** [comment]
Hey Adria, thanks for your pull request. I'm happy to merge it in, but just wondering whether activation of the user is really necessary. I thought I left it out so that you can discern between imported users that have actually activated their account and those who did not. Any thoughts?

**Comment by ajimix** [comment]
Well, when I import users it's because I want them to become active automatically, that's why I import them, otherwise, I would just invite them with the discourse interface no?

Also, I made this pull request because I read a comment in meta.discourse.com from yourself (I can't find the comment now) where you were telling someone to make a pull request with the activate and you will merge it so I went ahead and I did the PR :)

**Comment by safisher** [comment]
When I’m bulk importing users I want them automatically activated. I am using the bulk import to move a large list serve and if I require them to activate after importing, the bulk of my users would never get around to doing the activation and would fall off the list.

**Comment by vindia** [comment]
Ah you're right. It's been a while since I made this so can't remember all of it ;-).

I will merge this in after the weekend. Thanks for contributing!

**Comment by vindia** [comment]
Sorry, it took me a little longer to merge it in. I've made my changes myself too and chose to just replay your commit on the master branch and commit it instead of merging this PR. Thanks again for contributing, and if you have any other additions, please open a pull for them.

**Pull request closed without merging**
